name = "UnifiedCompiler"
uuid = "6d101ee7-afa6-416a-b797-8a652f7b3d1c"
version = "0.1.0"

[deps]
Compiler = "807dbc54-b67e-4c79-8afb-eafe4df6f2e1"
UnifiedIR = "71d3db7a-7671-43e7-8290-11c08a22bffa"

[sources]
Compiler = {path = "../Compiler"}
UnifiedIR = {path = "../UnifiedIR"}

[compat]
julia = "1.14"
