# The StyledStrings ANSI-write workload's compile set (wave 11): harvested
# from stock `--trace-compile` of a color-`IOContext` `print(io, styled"...")`
# + `printstyled` workload under `--pkgimages=no` (see unified_ansiwalk.jl's
# header). This is the `_ansi_writer` first-compile chain of
# scratchpad/wave10h/img_workload.log — the recursive cost-tower driver.
# Regenerate by re-harvesting when the workload drifts; the bench skips
# (and counts) any row that no longer resolves.
const ANSI_SIGS = [
    "Tuple{Type{Base.IOContext{IO_t} where IO_t<:IO}, Base.GenericIOBuffer{Memory{UInt8}}, Pair{Symbol, Bool}}",
    "Tuple{typeof(Base.escape_raw_string), String}",
    "Tuple{typeof(Base.unescape_string), String, NTuple{5, Char}}",
    "Tuple{Core.TypeEgal{StyledStrings.StyledMarkup.State}, String, Module}",
    "Tuple{Core.TypeEgal{Array{NamedTuple{(:message, :position, :hint), Tuple{Base.AnnotatedString{String}, Union{Nothing, Int64}, String}}, 1}}, UndefInitializer, Int64}",
    "Tuple{typeof(Base.:(∉)), Tuple{Char, Char}}",
    "Tuple{typeof(Base.:(∉)), Tuple{Char, Char, Char}}",
    "Tuple{typeof(Base.:(∉)), NTuple{6, Char}}",
    "Tuple{typeof(StyledStrings.StyledMarkup.run_state_machine!), StyledStrings.StyledMarkup.State}",
    "Tuple{typeof(Base.popfirst!), Base.Iterators.Stateful{Base.Iterators.IterableStatePairs{String}, Union{Nothing, Tuple{Pair{Int64, Char}, Int64}}}}",
    "Tuple{typeof(Base.indexed_iterate), Pair{Int64, Char}, Int64}",
    "Tuple{typeof(Base.indexed_iterate), Pair{Int64, Char}, Int64, Int64}",
    "Tuple{typeof(Base.last), Pair{Int64, Char}}",
    "Tuple{typeof(Base.in), Char, NTuple{4, Char}}",
    "Tuple{typeof(Base.:(∉)), Char, Tuple{Char, Char, Char}}",
    "Tuple{typeof(Base.:(∉)), Char, NTuple{6, Char}}",
    "Tuple{typeof(Base.first), Pair{Int64, Char}}",
    "Tuple{typeof(Base.deleteat!), Array{UInt8, 1}, Base.UnitRange{Int64}}",
    "Tuple{typeof(Base.setproperty!), StyledStrings.StyledMarkup.State, Symbol, Int64}",
    "Tuple{typeof(StyledStrings.StyledMarkup.read_while!), StyledStrings.StyledMarkup.var\"#read_inlineface!##1#read_inlineface!##2\", Base.Iterators.Stateful{Base.Iterators.IterableStatePairs{String}, Union{Nothing, Tuple{Pair{Int64, Char}, Int64}}}, Char}",
    "Tuple{typeof(StyledStrings.StyledMarkup.read_while!), Base.Fix{2, typeof(Base.:(∉)), NTuple{6, Char}}, Base.Iterators.Stateful{Base.Iterators.IterableStatePairs{String}, Union{Nothing, Tuple{Pair{Int64, Char}, Int64}}}, Char}",
    "Tuple{Core.TypeEgal{NamedTuple{(:foreground,), T} where T<:Tuple}, Tuple{StyledStrings.SimpleColor}}",
    "Tuple{typeof(Core.kwcall), NamedTuple{(:foreground,), Tuple{StyledStrings.SimpleColor}}, Core.TypeEgal{StyledStrings.Face}}",
    "Tuple{typeof(StyledStrings.StyledMarkup.interpolated!), StyledStrings.StyledMarkup.State, Int64, Char}",
    "Tuple{StyledStrings.StyledMarkup.var\"#addpart!##0#addpart!##1\", Base.UnitRange{Int64}, Tuple{Symbol, Symbol}}",
    "Tuple{StyledStrings.StyledMarkup.var\"#addpart!##0#addpart!##1\", Base.UnitRange{Int64}, Tuple{Symbol, StyledStrings.Face}}",
    "Tuple{Core.TypeEgal{Array{Tuple{Symbol, StyledStrings.Face}, 1}}, UndefInitializer, Tuple{Int64}}",
    "Tuple{typeof(Base.push!), Array{Tuple{Symbol, StyledStrings.Face}, 1}, Tuple{Symbol, StyledStrings.Face}}",
    "Tuple{typeof(Base.grow_to!), Array{Tuple{Symbol, StyledStrings.Face}, 1}, Base.Generator{Base.Iterators.Flatten{Array{Array{Tuple{Int64, Int64, Union{Expr, Symbol, Tuple{Symbol, Any}}}, 1}, 1}}, typeof(Base.last)}, Tuple{Int64, Array{Tuple{Int64, Int64, Union{Expr, Symbol, Tuple{Symbol, Any}}}, 1}, Int64}}",
    "Tuple{Core.TypeEgal{Base.Generator{I, F} where F where I}, StyledStrings.StyledMarkup.var\"#addpart!##8#addpart!##9\"{Symbol}, Array{Tuple{Symbol, StyledStrings.Face}, 1}}",
    "Tuple{typeof(Base.collect), Base.Generator{Array{Tuple{Symbol, StyledStrings.Face}, 1}, StyledStrings.StyledMarkup.var\"#addpart!##8#addpart!##9\"{Symbol}}}",
    "Tuple{typeof(Base.getproperty), StyledStrings.StyledMarkup.State, Symbol}",
    "Tuple{typeof(Base.isempty), Array{NamedTuple{(:message, :position, :hint), Tuple{Base.AnnotatedString{String}, Union{Nothing, Int64}, String}}, 1}}",
    "Tuple{Core.TypeEgal{NamedTuple{(:region,), T} where T<:Tuple}, Tuple{Base.UnitRange{Int64}}}",
    "Tuple{Core.TypeEgal{NamedTuple{(:label, :value), Tuple{Symbol, Any}}}, Tuple{Symbol, Symbol}}",
    "Tuple{typeof(Base.merge), NamedTuple{(:region,), Tuple{Base.UnitRange{Int64}}}, NamedTuple{(:label, :value), Tuple{Symbol, Any}}}",
    "Tuple{Core.TypeEgal{NamedTuple{(:label, :value), Tuple{Symbol, Any}}}, Tuple{Symbol, StyledStrings.Face}}",
    "Tuple{typeof(Base.vect), NamedTuple{(:region, :label, :value), Tuple{Base.UnitRange{Int64}, Symbol, Any}}, NamedTuple{(:region, :label, :value), Tuple{Base.UnitRange{Int64}, Symbol, Any}}}",
    "Tuple{Type{Base.AnnotatedString{S} where S<:AbstractString}, String, Array{NamedTuple{(:region, :label, :value), Tuple{Base.UnitRange{Int64}, Symbol, Any}}, 1}}",
    "Tuple{typeof(Base.string), Int64}",
    "Tuple{Core.TypeEgal{NamedTuple{(:region, :label, :value), Tuple{Base.UnitRange{Int64}, Symbol, Any}}}, Tuple{Base.UnitRange{Int64}, Symbol, StyledStrings.Face}}",
    "Tuple{Base.BottomRF{typeof(Base.:(+))}, Base._InitialValue, Int64}",
    "Tuple{typeof(Base.annotatedstring), Base.AnnotatedString{String}, Base.AnnotatedString{String}}",
    "Tuple{typeof(Base.:(|>)), Base.AnnotatedString{String}, typeof(StyledStrings.StyledMarkup.annotatedstring_optimize!)}",
    "Tuple{typeof(Base.get), Base.Dict{Tuple{Symbol, Any}, Int64}, Tuple{Symbol, Symbol}, Int64}",
    "Tuple{typeof(Base.setindex!), Base.Dict{Tuple{Symbol, Any}, Int64}, Int64, Tuple{Symbol, Symbol}}",
    "Tuple{typeof(Base._reverse_iter), NTuple{10, Symbol}}",
    "Tuple{Core.TypeEgal{NamedTuple{(:init,), T} where T<:Tuple}, Tuple{UInt64}}",
    "Tuple{typeof(Base.get), Base.Dict{Tuple{Symbol, Any}, Int64}, Tuple{Symbol, StyledStrings.Face}, Int64}",
    "Tuple{typeof(Base.setindex!), Base.Dict{Tuple{Symbol, Any}, Int64}, Int64, Tuple{Symbol, StyledStrings.Face}}",
    "Tuple{typeof(Base.print), Base.IOContext{Base.GenericIOBuffer{Memory{UInt8}}}, Base.AnnotatedString{String}}",
    "Tuple{typeof(Base.getproperty), NamedTuple{(:themes, :modifications, :current, :basecolors, :lock), Tuple{NamedTuple{(:base, :light, :dark), Tuple{Base.Dict{Symbol, StyledStrings.Face}, Base.Dict{Symbol, StyledStrings.Face}, Base.Dict{Symbol, StyledStrings.Face}}}, NamedTuple{(:base, :light, :dark), Tuple{Base.Dict{Symbol, StyledStrings.Face}, Base.Dict{Symbol, StyledStrings.Face}, Base.Dict{Symbol, StyledStrings.Face}}}, Base.ScopedValues.ScopedValue{Base.Dict{Symbol, StyledStrings.Face}}, Base.Dict{Symbol, NamedTuple{(:r, :g, :b), Tuple{UInt8, UInt8, UInt8}}}, Base.ReentrantLock}}, Symbol}",
    "Tuple{typeof(Base.getproperty), NamedTuple{(:base, :light, :dark), Tuple{Base.Dict{Symbol, StyledStrings.Face}, Base.Dict{Symbol, StyledStrings.Face}, Base.Dict{Symbol, StyledStrings.Face}}}, Symbol}",
    "Tuple{typeof(Base.unwrap_composed), Base.ComposedFunction{Base.Fix{2, typeof(Base.:(var\"==\")), Symbol}, typeof(Base.first)}}",
    "Tuple{typeof(Base.getproperty), NamedTuple{(:bold_weight, :dim_weight, :normal_weight, :start_italics, :end_italics, :start_underline, :end_underline, :start_reverse, :end_reverse, :start_strikethrough, :end_strikethrough), NTuple{11, String}}, Symbol}",
    "Tuple{typeof(Base.tail), Tuple{Nothing, Bool}}",
    "Tuple{typeof(Base.:(var\"==\")), Nothing, Bool}",
    "Tuple{Core.TypeEgal{StyledStrings.SimpleColor}, Symbol}",
    "Tuple{typeof(Base.getproperty), Base.ScopedValues.ScopedValue{Base.Dict{Symbol, StyledStrings.Face}}, Symbol}",
    "Tuple{typeof(Base.ScopedValues.hasdefault), Base.ScopedValues.ScopedValue{Base.Dict{Symbol, StyledStrings.Face}}}",
    "Tuple{Core.TypeEgal{Base.Some{Base.Dict{Symbol, StyledStrings.Face}}}, Base.Dict{Symbol, StyledStrings.Face}}",
    "Tuple{Core.TypeEgal{Base.Fix{1, F, T} where T where F}, typeof(Base.ScopedValues.getdefault), Base.ScopedValues.ScopedValue{Base.Dict{Symbol, StyledStrings.Face}}}",
    "Tuple{typeof(Base.literal_pow), typeof(Base.:(^)), Int64, Base.Val{3}}",
    "Tuple{typeof(Base.getproperty), Base.FilteringRF{StyledStrings.var\"#getface##2#getface##3\", Base.MappingRF{StyledStrings.var\"#getface##0#getface##1\", Base.MappingRF{typeof(StyledStrings._mergedface), Base.BottomRF{typeof(Base.merge)}}}}, Symbol}",
    "Tuple{typeof(Base.getproperty), Base.MappingRF{StyledStrings.var\"#getface##0#getface##1\", Base.MappingRF{typeof(StyledStrings._mergedface), Base.BottomRF{typeof(Base.merge)}}}, Symbol}",
    "Tuple{typeof(Base.getindex), NamedTuple{(:base, :light, :dark), Tuple{Base.Dict{Symbol, StyledStrings.Face}, Base.Dict{Symbol, StyledStrings.Face}, Base.Dict{Symbol, StyledStrings.Face}}}, Symbol}",
    "Tuple{typeof(Base.map), Core.TypeEgal{String}, NTuple{26, Symbol}}",
    "Tuple{typeof(Base.tail), NTuple{26, Symbol}}",
    "Tuple{typeof(Base.map), Core.TypeEgal{String}, NTuple{25, Symbol}}",
    "Tuple{typeof(Base.tail), NTuple{25, Symbol}}",
    "Tuple{typeof(Base.map), Core.TypeEgal{String}, NTuple{24, Symbol}}",
    "Tuple{typeof(Base.tail), NTuple{24, Symbol}}",
    "Tuple{typeof(Base.map), Core.TypeEgal{String}, NTuple{23, Symbol}}",
    "Tuple{typeof(Base.tail), NTuple{23, Symbol}}",
    "Tuple{typeof(Base.map), Core.TypeEgal{String}, NTuple{22, Symbol}}",
    "Tuple{typeof(Base.tail), NTuple{22, Symbol}}",
    "Tuple{typeof(Base.map), Core.TypeEgal{String}, NTuple{21, Symbol}}",
    "Tuple{typeof(Base.tail), NTuple{21, Symbol}}",
    "Tuple{typeof(Base.map), Core.TypeEgal{String}, NTuple{20, Symbol}}",
    "Tuple{typeof(Base.tail), NTuple{20, Symbol}}",
    "Tuple{typeof(Base.map), Core.TypeEgal{String}, NTuple{19, Symbol}}",
    "Tuple{typeof(Base.tail), NTuple{19, Symbol}}",
    "Tuple{typeof(Base.map), Core.TypeEgal{String}, NTuple{18, Symbol}}",
    "Tuple{typeof(Base.tail), NTuple{18, Symbol}}",
    "Tuple{typeof(Base.map), Core.TypeEgal{String}, NTuple{17, Symbol}}",
    "Tuple{typeof(Base.tail), NTuple{17, Symbol}}",
    "Tuple{typeof(Base.map), Core.TypeEgal{String}, NTuple{16, Symbol}}",
    "Tuple{typeof(Base.tail), NTuple{16, Symbol}}",
    "Tuple{typeof(Base.map), Core.TypeEgal{String}, NTuple{15, Symbol}}",
    "Tuple{typeof(Base.tail), NTuple{15, Symbol}}",
    "Tuple{typeof(Base.map), Core.TypeEgal{String}, NTuple{14, Symbol}}",
    "Tuple{typeof(Base.tail), NTuple{14, Symbol}}",
    "Tuple{typeof(Base.map), Core.TypeEgal{String}, NTuple{13, Symbol}}",
    "Tuple{typeof(Base.tail), NTuple{13, Symbol}}",
    "Tuple{typeof(Base.map), Core.TypeEgal{String}, NTuple{12, Symbol}}",
    "Tuple{typeof(Base.tail), NTuple{12, Symbol}}",
    "Tuple{typeof(Base.map), Core.TypeEgal{String}, NTuple{11, Symbol}}",
    "Tuple{typeof(Base.tail), NTuple{11, Symbol}}",
    "Tuple{typeof(Base.map), Core.TypeEgal{String}, NTuple{10, Symbol}}",
    "Tuple{typeof(Base.tail), NTuple{10, Symbol}}",
    "Tuple{typeof(Base.map), Core.TypeEgal{String}, NTuple{9, Symbol}}",
    "Tuple{typeof(Base.tail), NTuple{9, Symbol}}",
    "Tuple{typeof(Base.map), Core.TypeEgal{String}, NTuple{8, Symbol}}",
    "Tuple{typeof(Base.tail), NTuple{8, Symbol}}",
    "Tuple{typeof(Base.map), Core.TypeEgal{String}, NTuple{7, Symbol}}",
    "Tuple{typeof(Base.tail), NTuple{7, Symbol}}",
    "Tuple{typeof(Base.map), Core.TypeEgal{String}, NTuple{6, Symbol}}",
    "Tuple{typeof(Base.tail), NTuple{6, Symbol}}",
    "Tuple{typeof(Base.map), Core.TypeEgal{String}, NTuple{5, Symbol}}",
    "Tuple{typeof(Base.tail), NTuple{5, Symbol}}",
    "Tuple{typeof(Base.map), Core.TypeEgal{String}, NTuple{4, Symbol}}",
    "Tuple{typeof(Base.tail), NTuple{4, Symbol}}",
    "Tuple{typeof(Base.map), Core.TypeEgal{String}, Tuple{Symbol, Symbol, Symbol}}",
    "Tuple{typeof(Base.tail), NTuple{26, String}}",
    "Tuple{typeof(Base.tail), NTuple{25, String}}",
    "Tuple{typeof(Base.tail), NTuple{24, String}}",
    "Tuple{typeof(Base.tail), NTuple{23, String}}",
    "Tuple{typeof(Base.tail), NTuple{22, String}}",
    "Tuple{typeof(Base.tail), NTuple{21, String}}",
    "Tuple{typeof(Base.tail), NTuple{20, String}}",
    "Tuple{typeof(Base.tail), NTuple{19, String}}",
    "Tuple{typeof(Base.tail), NTuple{18, String}}",
    "Tuple{typeof(Base.tail), NTuple{17, String}}",
    "Tuple{typeof(Base.tail), NTuple{16, String}}",
    "Tuple{typeof(Base.tail), NTuple{15, String}}",
    "Tuple{typeof(Base.tail), NTuple{14, String}}",
    "Tuple{typeof(Base.tail), NTuple{13, String}}",
    "Tuple{typeof(Base.tail), NTuple{12, String}}",
    "Tuple{typeof(Base.AnnotatedDisplay.ansi_write), typeof(Base.write), Base.IOContext{Base.GenericIOBuffer{Memory{UInt8}}}, Base.AnnotatedString{String}}",
    "Tuple{typeof(Core.kwcall), NamedTuple{(:color, :bold), Tuple{Symbol, Bool}}, typeof(Base.printstyled), Base.IOContext{Base.GenericIOBuffer{Memory{UInt8}}}, String}",
    "Tuple{Core.TypeEgal{Base.Fix{1, F, T} where T where F}, typeof(StyledStrings.StyledMarkup.hygienic_eval), StyledStrings.StyledMarkup.State}",
    "Tuple{typeof(Base.map), Function, Array{Any, 1}}",
    "Tuple{Core.TypeEgal{Base.Generator{I, F} where F where I}, Base.Fix{1, typeof(StyledStrings.StyledMarkup.hygienic_eval), StyledStrings.StyledMarkup.State}, Array{Any, 1}}",
    "Tuple{typeof(Base.collect_similar), Array{Any, 1}, Base.Generator{Array{Any, 1}, Base.Fix{1, typeof(StyledStrings.StyledMarkup.hygienic_eval), StyledStrings.StyledMarkup.State}}}",
    "Tuple{Base.Fix{1, typeof(StyledStrings.StyledMarkup.hygienic_eval), StyledStrings.StyledMarkup.State}, Expr}",
    "Tuple{Core.TypeEgal{Array{Base.AnnotatedString{String}, 1}}, UndefInitializer, Tuple{Int64}}",
    "Tuple{typeof(Base.typejoin), Any, Core.TypeofBottom}",
    "Tuple{typeof(Base.collect_to_with_first!), Array{Base.AnnotatedString{String}, 1}, Base.AnnotatedString{String}, Base.Generator{Array{Any, 1}, Base.Fix{1, typeof(StyledStrings.StyledMarkup.hygienic_eval), StyledStrings.StyledMarkup.State}}, Int64}",
    "Tuple{typeof(Base.annotatedstring), Base.AnnotatedString{String}}",
]
