# The Test-loading workload's compile set (B1 target list): harvested from
# stock `--trace-compile` of `using Test; @testset ...` under
# `--pkgimages=no` (see unified_coldwalk.jl's header for the exact
# invocation), filtered to signatures resolvable after `using Test`.
# Regenerate by re-harvesting when the workload drifts; the bench skips
# (and counts) any row that no longer resolves.
const WORKLOAD_SIGS = [
    "Tuple{typeof(Base.something), Bool}",
    "Tuple{typeof(Base.open), Base.CmdRedirect, String, Base.PipeEndpoint}",
    "Tuple{typeof(Base.println), Base.IOContext{IO}, Vararg{String, 4}}",
    "Tuple{typeof(Base.println), Base.IOContext{IO}, String}",
    "Tuple{typeof(Test.testset_beginend_call), Tuple{String, Expr}, Expr, LineNumberNode}",
    "Tuple{typeof(Base.last), Tuple{Expr, Expr, Expr}}",
    "Tuple{typeof(Base.map), typeof(Base.esc), Tuple{Expr, Expr}}",
    "Tuple{typeof(Base.getproperty), Base.Generator{Base.Iterators.Filter{Test.var\"#@test##2#@test##3\", Tuple{}}, Test.var\"#@test##0#@test##1\"}, Symbol}",
    "Tuple{typeof(Base.getproperty), Base.Iterators.Filter{Test.var\"#@test##2#@test##3\", Tuple{}}, Symbol}",
    "Tuple{typeof(Base.collect), Base.Generator{Base.Iterators.Filter{Test.var\"#@test##2#@test##3\", Tuple{}}, Test.var\"#@test##0#@test##1\"}}",
    "Tuple{typeof(Base.getproperty), Base.Generator{Base.Iterators.Filter{Test.var\"#@test##6#@test##7\", Tuple{}}, Test.var\"#@test##4#@test##5\"}, Symbol}",
    "Tuple{typeof(Base.getproperty), Base.Iterators.Filter{Test.var\"#@test##6#@test##7\", Tuple{}}, Symbol}",
    "Tuple{typeof(Base.collect), Base.Generator{Base.Iterators.Filter{Test.var\"#@test##6#@test##7\", Tuple{}}, Test.var\"#@test##4#@test##5\"}}",
    "Tuple{typeof(Base.getproperty), Base.Generator{Base.Iterators.Filter{Test.var\"#@test##10#@test##11\", Tuple{}}, Test.var\"#@test##8#@test##9\"}, Symbol}",
    "Tuple{typeof(Base.getproperty), Base.Iterators.Filter{Test.var\"#@test##10#@test##11\", Tuple{}}, Symbol}",
    "Tuple{typeof(Base.collect), Base.Generator{Base.Iterators.Filter{Test.var\"#@test##10#@test##11\", Tuple{}}, Test.var\"#@test##8#@test##9\"}}",
    "Tuple{typeof(Base.indexed_iterate), Tuple{Array{Union{}, 1}, Symbol}, Int64}",
    "Tuple{typeof(Base.indexed_iterate), Tuple{Array{Union{}, 1}, Symbol}, Int64, Int64}",
    "Tuple{typeof(Base.length), Array{Union{}, 1}}",
    "Tuple{typeof(Test.test_expr!), String, Expr}",
    "Tuple{typeof(Test.get_test_result), Expr, LineNumberNode}",
    "Tuple{typeof(Base.first), String}",
    "Tuple{typeof(Test.get_testset_depth)}",
    "Tuple{typeof(Test._check_testset), Core.TypeEgal{Test.DefaultTestSet}, Expr}",
    "Tuple{Core.TypeEgal{NamedTuple{(:source,), T} where T<:Tuple}, Tuple{Symbol}}",
    "Tuple{typeof(Base.merge), NamedTuple{(:source,), Tuple{Symbol}}, Base.Dict{Symbol, Any}}",
    "Tuple{Core.TypeEgal{Base.Fix{1, F, T} where T where F}, typeof(Base.ScopedValues.getdefault), Base.ScopedValues.LazyScopedValue{Bool}}",
    "Tuple{typeof(Core.kwcall), NamedTuple{(:source,), Tuple{Symbol}}, Core.TypeEgal{Test.DefaultTestSet}, String}",
    "Tuple{typeof(Test.get_rng), Test.DefaultTestSet}",
    "Tuple{typeof(Test.set_rng!), Test.DefaultTestSet, Random.Xoshiro}",
    "Tuple{typeof(Test.print_testset_verbose), Symbol, Test.DefaultTestSet}",
    "Tuple{Core.TypeEgal{Pair{A, B} where B where A}, Base.ScopedValues.ScopedValue{Test.AbstractTestSet}, Test.DefaultTestSet}",
    "Tuple{Core.TypeEgal{Base.ScopedValues.Scope}, Base.ScopedValues.Scope, Pair{Base.ScopedValues.ScopedValue{Test.AbstractTestSet}, Test.DefaultTestSet}, Pair{Base.ScopedValues.ScopedValue{Int64}, Int64}}",
    "Tuple{typeof(Test.eval_test_comparison), Expr, Array{Any, 1}, LineNumberNode, Bool}",
    "Tuple{typeof(Base.ScopedValues.hasdefault), Base.ScopedValues.ScopedValue{Bool}}",
    "Tuple{typeof(Base.ScopedValues.getdefault), Base.ScopedValues.ScopedValue{Bool}}",
    "Tuple{Core.TypeEgal{Base.Some{Bool}}, Bool}",
    "Tuple{Core.TypeEgal{Base.Fix{1, F, T} where T where F}, typeof(Base.ScopedValues.getdefault), Base.ScopedValues.ScopedValue{Bool}}",
    "Tuple{Base.Fix{1, typeof(Base.ScopedValues.getdefault), Base.ScopedValues.ScopedValue{Bool}}}",
    "Tuple{Core.TypeEgal{NamedTuple{(:prefix,), T} where T<:Tuple}, Tuple{String}}",
    "Tuple{Core.TypeEgal{Test.FallbackTestSetException}, String}",
    "Tuple{typeof(Test.do_test), Test.Returned, Expr, Nothing}",
    "Tuple{typeof(Test.finish), Test.DefaultTestSet}",
    "Tuple{Core.TypeEgal{NamedTuple{(:bold, :color), T} where T<:Tuple}, Tuple{Bool, Symbol}}",
    "Tuple{typeof(Test.print_test_results), Base.PipeEndpoint, Test.DefaultTestSet, Int64}",
]
